// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yrpc_meta.proto

package com.github.m5.netutil.rpc.proto;

public final class YrpcProtos {
    private YrpcProtos() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface YrpcRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:netutil.YrpcRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string request_id = 1;</code>
         */
        java.lang.String getRequestId();

        /**
         * <code>string request_id = 1;</code>
         */
        com.google.protobuf.ByteString
        getRequestIdBytes();

        /**
         * <code>string group = 2;</code>
         */
        java.lang.String getGroup();

        /**
         * <code>string group = 2;</code>
         */
        com.google.protobuf.ByteString
        getGroupBytes();

        /**
         * <code>string version = 3;</code>
         */
        java.lang.String getVersion();

        /**
         * <code>string version = 3;</code>
         */
        com.google.protobuf.ByteString
        getVersionBytes();

        /**
         * <code>string interface_name = 4;</code>
         */
        java.lang.String getInterfaceName();

        /**
         * <code>string interface_name = 4;</code>
         */
        com.google.protobuf.ByteString
        getInterfaceNameBytes();

        /**
         * <code>string method_name = 5;</code>
         */
        java.lang.String getMethodName();

        /**
         * <code>string method_name = 5;</code>
         */
        com.google.protobuf.ByteString
        getMethodNameBytes();

        /**
         * <code>repeated bytes params = 6;</code>
         */
        java.util.List<com.google.protobuf.ByteString> getParamsList();

        /**
         * <code>repeated bytes params = 6;</code>
         */
        int getParamsCount();

        /**
         * <code>repeated bytes params = 6;</code>
         */
        com.google.protobuf.ByteString getParams(int index);
    }

    /**
     * Protobuf type {@code netutil.YrpcRequest}
     */
    public static final class YrpcRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:netutil.YrpcRequest)
            YrpcRequestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use YrpcRequest.newBuilder() to construct.
        private YrpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private YrpcRequest() {
            requestId_ = "";
            group_ = "";
            version_ = "";
            interfaceName_ = "";
            methodName_ = "";
            params_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private YrpcRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            requestId_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            group_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            version_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            interfaceName_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            methodName_ = s;
                            break;
                        }
                        case 50: {
                            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                                params_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                                mutable_bitField0_ |= 0x00000020;
                            }
                            params_.add(input.readBytes());
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                    params_ = java.util.Collections.unmodifiableList(params_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.github.m5.netutil.rpc.proto.YrpcProtos.internal_static_netutil_YrpcRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.github.m5.netutil.rpc.proto.YrpcProtos.internal_static_netutil_YrpcRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest.class, com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest.Builder.class);
        }

        private int bitField0_;
        public static final int REQUEST_ID_FIELD_NUMBER = 1;
        private volatile java.lang.Object requestId_;

        /**
         * <code>string request_id = 1;</code>
         */
        public java.lang.String getRequestId() {
            java.lang.Object ref = requestId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                requestId_ = s;
                return s;
            }
        }

        /**
         * <code>string request_id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getRequestIdBytes() {
            java.lang.Object ref = requestId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                requestId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int GROUP_FIELD_NUMBER = 2;
        private volatile java.lang.Object group_;

        /**
         * <code>string group = 2;</code>
         */
        public java.lang.String getGroup() {
            java.lang.Object ref = group_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                group_ = s;
                return s;
            }
        }

        /**
         * <code>string group = 2;</code>
         */
        public com.google.protobuf.ByteString
        getGroupBytes() {
            java.lang.Object ref = group_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                group_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int VERSION_FIELD_NUMBER = 3;
        private volatile java.lang.Object version_;

        /**
         * <code>string version = 3;</code>
         */
        public java.lang.String getVersion() {
            java.lang.Object ref = version_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                version_ = s;
                return s;
            }
        }

        /**
         * <code>string version = 3;</code>
         */
        public com.google.protobuf.ByteString
        getVersionBytes() {
            java.lang.Object ref = version_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                version_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int INTERFACE_NAME_FIELD_NUMBER = 4;
        private volatile java.lang.Object interfaceName_;

        /**
         * <code>string interface_name = 4;</code>
         */
        public java.lang.String getInterfaceName() {
            java.lang.Object ref = interfaceName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                interfaceName_ = s;
                return s;
            }
        }

        /**
         * <code>string interface_name = 4;</code>
         */
        public com.google.protobuf.ByteString
        getInterfaceNameBytes() {
            java.lang.Object ref = interfaceName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                interfaceName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int METHOD_NAME_FIELD_NUMBER = 5;
        private volatile java.lang.Object methodName_;

        /**
         * <code>string method_name = 5;</code>
         */
        public java.lang.String getMethodName() {
            java.lang.Object ref = methodName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                methodName_ = s;
                return s;
            }
        }

        /**
         * <code>string method_name = 5;</code>
         */
        public com.google.protobuf.ByteString
        getMethodNameBytes() {
            java.lang.Object ref = methodName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                methodName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PARAMS_FIELD_NUMBER = 6;
        private java.util.List<com.google.protobuf.ByteString> params_;

        /**
         * <code>repeated bytes params = 6;</code>
         */
        public java.util.List<com.google.protobuf.ByteString>
        getParamsList() {
            return params_;
        }

        /**
         * <code>repeated bytes params = 6;</code>
         */
        public int getParamsCount() {
            return params_.size();
        }

        /**
         * <code>repeated bytes params = 6;</code>
         */
        public com.google.protobuf.ByteString getParams(int index) {
            return params_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getRequestIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
            }
            if (!getGroupBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, group_);
            }
            if (!getVersionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
            }
            if (!getInterfaceNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, interfaceName_);
            }
            if (!getMethodNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, methodName_);
            }
            for (int i = 0; i < params_.size(); i++) {
                output.writeBytes(6, params_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getRequestIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
            }
            if (!getGroupBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, group_);
            }
            if (!getVersionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
            }
            if (!getInterfaceNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, interfaceName_);
            }
            if (!getMethodNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, methodName_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < params_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(params_.get(i));
                }
                size += dataSize;
                size += 1 * getParamsList().size();
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest)) {
                return super.equals(obj);
            }
            com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest other = (com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest) obj;

            boolean result = true;
            result = result && getRequestId()
                    .equals(other.getRequestId());
            result = result && getGroup()
                    .equals(other.getGroup());
            result = result && getVersion()
                    .equals(other.getVersion());
            result = result && getInterfaceName()
                    .equals(other.getInterfaceName());
            result = result && getMethodName()
                    .equals(other.getMethodName());
            result = result && getParamsList()
                    .equals(other.getParamsList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
            hash = (53 * hash) + getRequestId().hashCode();
            hash = (37 * hash) + GROUP_FIELD_NUMBER;
            hash = (53 * hash) + getGroup().hashCode();
            hash = (37 * hash) + VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getVersion().hashCode();
            hash = (37 * hash) + INTERFACE_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getInterfaceName().hashCode();
            hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getMethodName().hashCode();
            if (getParamsCount() > 0) {
                hash = (37 * hash) + PARAMS_FIELD_NUMBER;
                hash = (53 * hash) + getParamsList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code netutil.YrpcRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:netutil.YrpcRequest)
                com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.github.m5.netutil.rpc.proto.YrpcProtos.internal_static_netutil_YrpcRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.github.m5.netutil.rpc.proto.YrpcProtos.internal_static_netutil_YrpcRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest.class, com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest.Builder.class);
            }

            // Construct using com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                requestId_ = "";

                group_ = "";

                version_ = "";

                interfaceName_ = "";

                methodName_ = "";

                params_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000020);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.github.m5.netutil.rpc.proto.YrpcProtos.internal_static_netutil_YrpcRequest_descriptor;
            }

            @java.lang.Override
            public com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest getDefaultInstanceForType() {
                return com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest.getDefaultInstance();
            }

            @java.lang.Override
            public com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest build() {
                com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest buildPartial() {
                com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest result = new com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.requestId_ = requestId_;
                result.group_ = group_;
                result.version_ = version_;
                result.interfaceName_ = interfaceName_;
                result.methodName_ = methodName_;
                if (((bitField0_ & 0x00000020) == 0x00000020)) {
                    params_ = java.util.Collections.unmodifiableList(params_);
                    bitField0_ = (bitField0_ & ~0x00000020);
                }
                result.params_ = params_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest) {
                    return mergeFrom((com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest other) {
                if (other == com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest.getDefaultInstance()) return this;
                if (!other.getRequestId().isEmpty()) {
                    requestId_ = other.requestId_;
                    onChanged();
                }
                if (!other.getGroup().isEmpty()) {
                    group_ = other.group_;
                    onChanged();
                }
                if (!other.getVersion().isEmpty()) {
                    version_ = other.version_;
                    onChanged();
                }
                if (!other.getInterfaceName().isEmpty()) {
                    interfaceName_ = other.interfaceName_;
                    onChanged();
                }
                if (!other.getMethodName().isEmpty()) {
                    methodName_ = other.methodName_;
                    onChanged();
                }
                if (!other.params_.isEmpty()) {
                    if (params_.isEmpty()) {
                        params_ = other.params_;
                        bitField0_ = (bitField0_ & ~0x00000020);
                    } else {
                        ensureParamsIsMutable();
                        params_.addAll(other.params_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object requestId_ = "";

            /**
             * <code>string request_id = 1;</code>
             */
            public java.lang.String getRequestId() {
                java.lang.Object ref = requestId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    requestId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string request_id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getRequestIdBytes() {
                java.lang.Object ref = requestId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    requestId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string request_id = 1;</code>
             */
            public Builder setRequestId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                requestId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string request_id = 1;</code>
             */
            public Builder clearRequestId() {

                requestId_ = getDefaultInstance().getRequestId();
                onChanged();
                return this;
            }

            /**
             * <code>string request_id = 1;</code>
             */
            public Builder setRequestIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                requestId_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object group_ = "";

            /**
             * <code>string group = 2;</code>
             */
            public java.lang.String getGroup() {
                java.lang.Object ref = group_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    group_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string group = 2;</code>
             */
            public com.google.protobuf.ByteString
            getGroupBytes() {
                java.lang.Object ref = group_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    group_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string group = 2;</code>
             */
            public Builder setGroup(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                group_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string group = 2;</code>
             */
            public Builder clearGroup() {

                group_ = getDefaultInstance().getGroup();
                onChanged();
                return this;
            }

            /**
             * <code>string group = 2;</code>
             */
            public Builder setGroupBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                group_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object version_ = "";

            /**
             * <code>string version = 3;</code>
             */
            public java.lang.String getVersion() {
                java.lang.Object ref = version_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    version_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string version = 3;</code>
             */
            public com.google.protobuf.ByteString
            getVersionBytes() {
                java.lang.Object ref = version_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    version_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string version = 3;</code>
             */
            public Builder setVersion(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                version_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string version = 3;</code>
             */
            public Builder clearVersion() {

                version_ = getDefaultInstance().getVersion();
                onChanged();
                return this;
            }

            /**
             * <code>string version = 3;</code>
             */
            public Builder setVersionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                version_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object interfaceName_ = "";

            /**
             * <code>string interface_name = 4;</code>
             */
            public java.lang.String getInterfaceName() {
                java.lang.Object ref = interfaceName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    interfaceName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string interface_name = 4;</code>
             */
            public com.google.protobuf.ByteString
            getInterfaceNameBytes() {
                java.lang.Object ref = interfaceName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    interfaceName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string interface_name = 4;</code>
             */
            public Builder setInterfaceName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                interfaceName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string interface_name = 4;</code>
             */
            public Builder clearInterfaceName() {

                interfaceName_ = getDefaultInstance().getInterfaceName();
                onChanged();
                return this;
            }

            /**
             * <code>string interface_name = 4;</code>
             */
            public Builder setInterfaceNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                interfaceName_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object methodName_ = "";

            /**
             * <code>string method_name = 5;</code>
             */
            public java.lang.String getMethodName() {
                java.lang.Object ref = methodName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    methodName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string method_name = 5;</code>
             */
            public com.google.protobuf.ByteString
            getMethodNameBytes() {
                java.lang.Object ref = methodName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    methodName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string method_name = 5;</code>
             */
            public Builder setMethodName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                methodName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string method_name = 5;</code>
             */
            public Builder clearMethodName() {

                methodName_ = getDefaultInstance().getMethodName();
                onChanged();
                return this;
            }

            /**
             * <code>string method_name = 5;</code>
             */
            public Builder setMethodNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                methodName_ = value;
                onChanged();
                return this;
            }

            private java.util.List<com.google.protobuf.ByteString> params_ = java.util.Collections.emptyList();

            private void ensureParamsIsMutable() {
                if (!((bitField0_ & 0x00000020) == 0x00000020)) {
                    params_ = new java.util.ArrayList<com.google.protobuf.ByteString>(params_);
                    bitField0_ |= 0x00000020;
                }
            }

            /**
             * <code>repeated bytes params = 6;</code>
             */
            public java.util.List<com.google.protobuf.ByteString>
            getParamsList() {
                return java.util.Collections.unmodifiableList(params_);
            }

            /**
             * <code>repeated bytes params = 6;</code>
             */
            public int getParamsCount() {
                return params_.size();
            }

            /**
             * <code>repeated bytes params = 6;</code>
             */
            public com.google.protobuf.ByteString getParams(int index) {
                return params_.get(index);
            }

            /**
             * <code>repeated bytes params = 6;</code>
             */
            public Builder setParams(
                    int index, com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureParamsIsMutable();
                params_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes params = 6;</code>
             */
            public Builder addParams(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureParamsIsMutable();
                params_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes params = 6;</code>
             */
            public Builder addAllParams(
                    java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
                ensureParamsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, params_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes params = 6;</code>
             */
            public Builder clearParams() {
                params_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000020);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:netutil.YrpcRequest)
        }

        // @@protoc_insertion_point(class_scope:netutil.YrpcRequest)
        private static final com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest();
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<YrpcRequest>
                PARSER = new com.google.protobuf.AbstractParser<YrpcRequest>() {
            @java.lang.Override
            public YrpcRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new YrpcRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<YrpcRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<YrpcRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface YrpcResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:netutil.YrpcResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string request_id = 1;</code>
         */
        java.lang.String getRequestId();

        /**
         * <code>string request_id = 1;</code>
         */
        com.google.protobuf.ByteString
        getRequestIdBytes();

        /**
         * <code>bytes result = 2;</code>
         */
        com.google.protobuf.ByteString getResult();

        /**
         * <code>string err_msg = 3;</code>
         */
        java.lang.String getErrMsg();

        /**
         * <code>string err_msg = 3;</code>
         */
        com.google.protobuf.ByteString
        getErrMsgBytes();
    }

    /**
     * Protobuf type {@code netutil.YrpcResponse}
     */
    public static final class YrpcResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:netutil.YrpcResponse)
            YrpcResponseOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use YrpcResponse.newBuilder() to construct.
        private YrpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private YrpcResponse() {
            requestId_ = "";
            result_ = com.google.protobuf.ByteString.EMPTY;
            errMsg_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private YrpcResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            requestId_ = s;
                            break;
                        }
                        case 18: {

                            result_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            errMsg_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.github.m5.netutil.rpc.proto.YrpcProtos.internal_static_netutil_YrpcResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.github.m5.netutil.rpc.proto.YrpcProtos.internal_static_netutil_YrpcResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse.class, com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse.Builder.class);
        }

        public static final int REQUEST_ID_FIELD_NUMBER = 1;
        private volatile java.lang.Object requestId_;

        /**
         * <code>string request_id = 1;</code>
         */
        public java.lang.String getRequestId() {
            java.lang.Object ref = requestId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                requestId_ = s;
                return s;
            }
        }

        /**
         * <code>string request_id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getRequestIdBytes() {
            java.lang.Object ref = requestId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                requestId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int RESULT_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString result_;

        /**
         * <code>bytes result = 2;</code>
         */
        public com.google.protobuf.ByteString getResult() {
            return result_;
        }

        public static final int ERR_MSG_FIELD_NUMBER = 3;
        private volatile java.lang.Object errMsg_;

        /**
         * <code>string err_msg = 3;</code>
         */
        public java.lang.String getErrMsg() {
            java.lang.Object ref = errMsg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                errMsg_ = s;
                return s;
            }
        }

        /**
         * <code>string err_msg = 3;</code>
         */
        public com.google.protobuf.ByteString
        getErrMsgBytes() {
            java.lang.Object ref = errMsg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                errMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getRequestIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
            }
            if (!result_.isEmpty()) {
                output.writeBytes(2, result_);
            }
            if (!getErrMsgBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errMsg_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getRequestIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
            }
            if (!result_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, result_);
            }
            if (!getErrMsgBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errMsg_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse)) {
                return super.equals(obj);
            }
            com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse other = (com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse) obj;

            boolean result = true;
            result = result && getRequestId()
                    .equals(other.getRequestId());
            result = result && getResult()
                    .equals(other.getResult());
            result = result && getErrMsg()
                    .equals(other.getErrMsg());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
            hash = (53 * hash) + getRequestId().hashCode();
            hash = (37 * hash) + RESULT_FIELD_NUMBER;
            hash = (53 * hash) + getResult().hashCode();
            hash = (37 * hash) + ERR_MSG_FIELD_NUMBER;
            hash = (53 * hash) + getErrMsg().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code netutil.YrpcResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:netutil.YrpcResponse)
                com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.github.m5.netutil.rpc.proto.YrpcProtos.internal_static_netutil_YrpcResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.github.m5.netutil.rpc.proto.YrpcProtos.internal_static_netutil_YrpcResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse.class, com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse.Builder.class);
            }

            // Construct using com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                requestId_ = "";

                result_ = com.google.protobuf.ByteString.EMPTY;

                errMsg_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.github.m5.netutil.rpc.proto.YrpcProtos.internal_static_netutil_YrpcResponse_descriptor;
            }

            @java.lang.Override
            public com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse getDefaultInstanceForType() {
                return com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse.getDefaultInstance();
            }

            @java.lang.Override
            public com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse build() {
                com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse buildPartial() {
                com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse result = new com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse(this);
                result.requestId_ = requestId_;
                result.result_ = result_;
                result.errMsg_ = errMsg_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse) {
                    return mergeFrom((com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse other) {
                if (other == com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse.getDefaultInstance()) return this;
                if (!other.getRequestId().isEmpty()) {
                    requestId_ = other.requestId_;
                    onChanged();
                }
                if (other.getResult() != com.google.protobuf.ByteString.EMPTY) {
                    setResult(other.getResult());
                }
                if (!other.getErrMsg().isEmpty()) {
                    errMsg_ = other.errMsg_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object requestId_ = "";

            /**
             * <code>string request_id = 1;</code>
             */
            public java.lang.String getRequestId() {
                java.lang.Object ref = requestId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    requestId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string request_id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getRequestIdBytes() {
                java.lang.Object ref = requestId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    requestId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string request_id = 1;</code>
             */
            public Builder setRequestId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                requestId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string request_id = 1;</code>
             */
            public Builder clearRequestId() {

                requestId_ = getDefaultInstance().getRequestId();
                onChanged();
                return this;
            }

            /**
             * <code>string request_id = 1;</code>
             */
            public Builder setRequestIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                requestId_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes result = 2;</code>
             */
            public com.google.protobuf.ByteString getResult() {
                return result_;
            }

            /**
             * <code>bytes result = 2;</code>
             */
            public Builder setResult(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                result_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes result = 2;</code>
             */
            public Builder clearResult() {

                result_ = getDefaultInstance().getResult();
                onChanged();
                return this;
            }

            private java.lang.Object errMsg_ = "";

            /**
             * <code>string err_msg = 3;</code>
             */
            public java.lang.String getErrMsg() {
                java.lang.Object ref = errMsg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    errMsg_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string err_msg = 3;</code>
             */
            public com.google.protobuf.ByteString
            getErrMsgBytes() {
                java.lang.Object ref = errMsg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    errMsg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string err_msg = 3;</code>
             */
            public Builder setErrMsg(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                errMsg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string err_msg = 3;</code>
             */
            public Builder clearErrMsg() {

                errMsg_ = getDefaultInstance().getErrMsg();
                onChanged();
                return this;
            }

            /**
             * <code>string err_msg = 3;</code>
             */
            public Builder setErrMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                errMsg_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:netutil.YrpcResponse)
        }

        // @@protoc_insertion_point(class_scope:netutil.YrpcResponse)
        private static final com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse();
        }

        public static com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<YrpcResponse>
                PARSER = new com.google.protobuf.AbstractParser<YrpcResponse>() {
            @java.lang.Override
            public YrpcResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new YrpcResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<YrpcResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<YrpcResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.github.m5.netutil.rpc.proto.YrpcProtos.YrpcResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_netutil_YrpcRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_netutil_YrpcRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_netutil_YrpcResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_netutil_YrpcResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017yrpc_meta.proto\022\007netutil\"~\n\013YrpcReques" +
                        "t\022\022\n\nrequest_id\030\001 \001(\t\022\r\n\005group\030\002 \001(\t\022\017\n\007" +
                        "version\030\003 \001(\t\022\026\n\016interface_name\030\004 \001(\t\022\023\n" +
                        "\013method_name\030\005 \001(\t\022\016\n\006params\030\006 \003(\014\"C\n\014Yr" +
                        "pcResponse\022\022\n\nrequest_id\030\001 \001(\t\022\016\n\006result" +
                        "\030\002 \001(\014\022\017\n\007err_msg\030\003 \001(\tB-\n\037com.github.m5" +
                        ".netutil.rpc.protoB\nYrpcProtosb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_netutil_YrpcRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_netutil_YrpcRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_netutil_YrpcRequest_descriptor,
                new java.lang.String[]{"RequestId", "Group", "Version", "InterfaceName", "MethodName", "Params",});
        internal_static_netutil_YrpcResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_netutil_YrpcResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_netutil_YrpcResponse_descriptor,
                new java.lang.String[]{"RequestId", "Result", "ErrMsg",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
